### ISSUE TITLE
Errors on Quadro P6000

### ISSUE THREAD

**Issue by jayavanth** [gunrock/gunrock#219]
When I run any of the gunrock(dev branch) apps on Quadro P6000 I get errors like this:

> Using  1 GPU: [ 0 ].
> [../../gunrock/util/array_utils.cuh, 176 @ gpu 0] cuda_props cudaHostRegister failed. (CUDA error 30: unknown error)
> [../../gunrock/util/array_utils.cuh, 176 @ gpu 0] work_progress cudaHostRegister failed. (CUDA error 30: unknown error)
> [../../gunrock/util/array_utils.cuh, 176 @ gpu 0] enactor_stats cudaHostRegister failed. (CUDA error 30: unknown error)
> [../../gunrock/util/array_utils.cuh, 176 @ gpu 0] frontier_attribute cudaHostRegister failed. (CUDA error 30: unknown error)
> [../../gunrock/util/array_utils.cuh, 176 @ gpu 0] output_length cudaHostRegister failed. (CUDA error 30: unknown error)
> __________________________
> [../../gunrock/oprtr/advance/kernel.cuh, 151 @ gpu 0] cudaMemcpyAsync failed (CUDA error 11: invalid argument)
> [../../gunrock/util/sort_utils.cuh, 108 @ gpu 0] cub::DeviceRadixSort::SortPairsDescending failed (CUDA error 11: invalid argument)

This GPU has CC 6.1. Is gunrock tested on this CC?

**Comment by neoblizz** [comment]
Yes, please switch to `pre-release` branch and make sure you have latest CUDA 8.0 and the latest drivers. This `cudaHostRegister` bug was fixed in the latest CUDA release for pascal arch.

**Comment by neoblizz** [comment]
Code line where CC 6.1 is enabled in `pre-release`: https://github.com/gunrock/gunrock/blob/pre-release/CMakeLists.txt#L188

**Comment by jayavanth** [comment]
@neoblizz I have already enabled CC 6.1 in the dev branch in the CMakeFiles.txt and tests/BaseMakeFile. I still get this issue. I'll switch to pre-release and see if that works.

**Comment by jayavanth** [comment]
@neoblizz I updated to pre-release and I'm getting these errors:
Using 1 GPU(s): [ 0 ].
> [../../gunrock/util/array_utils.cuh, 176 @ gpu 0] in_length_out cudaHostRegister failed. (CUDA error 30: unknown error)
> [test_pr.cu, 632 @ gpu 0] PR Problem Init failed (CUDA error 30: unknown error)
I ran sssp and pagerank tests

**Comment by jowens** [comment]
What driver are you running? 367.48 fixed this issue for us, which was broken in 367.44.

**Comment by neoblizz** [comment]
@jayavanth can you please post what CUDA & driver version are you using? I would highly recommend updating CUDA 8 if you haven't already, because when we encountered this problem, it was an NVIDIA's bug and they fixed it in the latest CUDA update.

**Comment by jayavanth** [comment]
I'm running 370.28 driver with CUDA 8.0.44

**Comment by jowens** [comment]
I'll ping NVIDIA colleagues about this.

**Comment by jowens** [comment]
@jayavanth what OS?

**Comment by jayavanth** [comment]
Ubuntu 16.04

**Comment by jowens** [comment]
NVIDIA: "I would file a bug ASAP." @jayavanth, that's on you.

In doing so, I would make note of the fix NVIDIA put in between 367.44 and 367.48, and ask if the same issue is present in 370.28.

**Comment by jayavanth** [comment]
Thanks, @jowens. I filed a bug.

**Comment by neoblizz** [comment]
@jayavanth were you able to get any input on this? They now have newer drivers available, any feedback on this will be appreciated!
```
Version:	R375 U7 (377.35)  WHQL
Release Date:	2017.5.9
Operating System:	Windows 10 64-bit
Language:	English (US)
File Size:	264.69 MB
```

**Comment by neoblizz** [comment]
Closing this issue due to inactivity, the above driver update should have resolved it, open the issue again if that is not the case.
